using System.Collections.Generic;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._HorizonNova.Humanoid;

/// <summary>
/// Horizon Nova: the markings of a single body region, split into tabs per marking category.
/// Port of the Wega organ marking picker (Content.Client/Humanoid/OrganMarkingPicker.xaml.cs),
/// with the organ concept mapped onto <see cref="MarkingRegion"/> and the layers onto
/// <see cref="MarkingCategories"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OrganMarkingPicker : Control
{
    private readonly MarkingsViewModel _markingsModel;
    private readonly HashSet<MarkingCategories> _layers;

    public bool Empty => LayerTabs.ChildCount == 0;

    public OrganMarkingPicker(MarkingsViewModel markingsModel, MarkingRegion organ, HashSet<MarkingCategories> layers)
    {
        RobustXamlLoader.Load(this);

        _markingsModel = markingsModel;
        _layers = layers;

        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.OrganDataChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.OrganDataChanged -= UpdateMarkings;
    }

    private void UpdateMarkings()
    {
        LayerTabs.RemoveAllChildren();

        var i = 0;
        foreach (var layer in _layers)
        {
            var allMarkings = _markingsModel.GetAvailable(layer);
            var control = new LayerMarkingPicker(_markingsModel, layer, allMarkings);
            LayerTabs.AddChild(control);

            if (Loc.TryGetString($"markings-layer-{layer}", out var layerTitle))
                LayerTabs.SetTabTitle(i, layerTitle);
            else
                LayerTabs.SetTabTitle(i, Loc.GetString($"markings-category-{layer}"));

            i++;
        }

        LayerTabs.TabsVisible = i > 1;
    }
}
