using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _protomanager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        private readonly Button _createNewCharacterButton;
        private readonly HumanoidProfileEditor _profileEditor;
        private readonly CompanySelectorGui _companySelector;
        private bool _showingCompanySelector;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;
        public event Action<HumanoidCharacterProfile, int>? Save;

        public HumanoidCharacterProfile? EditedProfile => _showingCompanySelector ? _companySelector.Profile : _profileEditor.Profile;
        public int? EditedSlot => _showingCompanySelector ? _companySelector.CharacterSlot : _profileEditor.CharacterSlot;
        public bool IsDirty => _showingCompanySelector ? _companySelector.IsDirty : _profileEditor.IsDirty;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _profileEditor = profileEditor;
            _companySelector = new CompanySelectorGui();

            var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(21, 21, 21, 88)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
                HorizontalExpand = true,
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            _companySelector.Save += (profile, slot) => Save?.Invoke(profile, slot);

            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();

            StatsButton.OnPressed += _ => new PlaytimeStatsWindow().OpenCentered();

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);
        }

        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            _profileEditor.SetProfile(profile, slot);
            _companySelector.SetProfile(profile, slot);
            UpdateEditorView(profile);
        }

        private void UpdateEditorView(HumanoidCharacterProfile? profile)
        {
            var shouldShowSelector = ShouldShowCompanySelector(profile);
            var nextControl = shouldShowSelector ? (Control) _companySelector : _profileEditor;

            if (CharEditor.ChildCount > 0 && ReferenceEquals(CharEditor.Children[0], nextControl))
            {
                _showingCompanySelector = shouldShowSelector;
                return;
            }

            CharEditor.RemoveAllChildren();
            CharEditor.AddChild(nextControl);
            _showingCompanySelector = shouldShowSelector;
        }

        private bool ShouldShowCompanySelector(HumanoidCharacterProfile? profile)
        {
            // Factions/companies were removed (only the "None" placeholder prototype remains),
            // so the selector has nothing to offer anymore - always go straight to personalization.
            return false;
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            Characters.DisposeAllChildren();

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", _preferencesManager.Settings!.MaxCharacterSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;

            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                numberOfFullSlots++;
                var characterPickerButton = new CharacterPickerButton(_entManager,
                    _protomanager,
                    characterButtonsGroup,
                    character,
                    slot == selectedSlot);

                Characters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };
            }

            _createNewCharacterButton.Disabled = numberOfFullSlots >= _preferencesManager.Settings.MaxCharacterSlots;
            Characters.AddChild(_createNewCharacterButton);
        }
    }
}
