- type: dungeonConfig
  id: LuaMineshaft
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - LuaHub
    - LuaCluster
    - LuaGrid
    - LuaHive

  - !type:CorridorDunGen
    width: 3
    pathLimit: 8192
    tile: FloorCaveDrought

  - !type:DungeonEntranceDunGen
    count: 4
    tile: FloorCaveDrought
    contents: NFMiningAirlock

  - !type:RoomEntranceDunGen
    tile: FloorCaveDrought
    contents: NFMiningAirlock

  - !type:BoundaryWallDunGen
    wall: WallRock
    cornerWall: WallRock
    tile: FloorCaveDrought

- type: dungeonConfig
  id: LuaOutpost
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFSalvageOutpost
    presets:
    - LuaCross
    - LuaHub
    - LuaWings

  - !type:CorridorDunGen
    width: 3
    tile: FloorDark

  - !type:DungeonEntranceDunGen
    count: 3
    tile: FloorDark
    contents: NFMiningAirlock

  - !type:RoomEntranceDunGen
    tile: FloorDark
    contents: NFMiningAirlock

  - !type:EntranceFlankDunGen
    tile: FloorDark
    contents: NFMiningWindow

  - !type:ExternalWindowDunGen
    tile: FloorDark
    contents: NFMiningWindow

  - !type:WallMountDunGen
    contents: NFBaseWallMounts
    tile: FloorDark

  - !type:BoundaryWallDunGen
    wall: WallMining
    cornerWall: WallMining
    tile: FloorDark

  - !type:JunctionDunGen
    width: 3
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: LuaCaveFactory
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFCaveFactory
    presets:
    - LuaGrid
    - LuaCascade
    - LuaLongmarch
    - LuaBucket
    - LuaCluster

  - !type:CorridorDunGen
    width: 3
    tile: FloorTechMaint

  - !type:DungeonEntranceDunGen
    count: 4
    tile: FloorTechMaint
    contents: NFLavaBrigEntrance

  - !type:RoomEntranceDunGen
    tile: FloorTechMaint
    contents: NFBaseAirlock

  - !type:WallMountDunGen
    contents: NFCaveFactoryWallMounts
    tile: FloorTechMaint

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorTechMaint

  - !type:JunctionDunGen
    width: 3
    tile: FloorTechMaint
    contents: NFBaseAirlock

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: LuaExperiment
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFSalvageExperiment
    presets:
    - LuaGrid
    - LuaSpine
    - LuaFork
    - LuaRing

  - !type:CorridorDunGen
    width: 3
    tile: FloorWhite

  - !type:DungeonEntranceDunGen
    count: 3
    tile: FloorWhite
    contents: NFLavaBrigEntrance

  - !type:RoomEntranceDunGen
    tile: FloorWhite
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorWhite
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorWhite
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFMedSciWallMounts
    tile: FloorWhite

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorWhite

  - !type:JunctionDunGen
    width: 3
    tile: FloorWhite
    contents: NFBaseAirlock

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: LuaLavaBrig
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFLavaBrig
    presets:
    - LuaGateHex
    - LuaCross
    - LuaHive

  - !type:CorridorDunGen
    width: 3
    tile: FloorDark

  - !type:DungeonEntranceDunGen
    count: 3
    tile: FloorDark
    contents: NFLavaBrigEntrance

  - !type:RoomEntranceDunGen
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:BoundaryWallDunGen
    wall: WallReinforced
    cornerWall: WallReinforced
    tile: FloorDark

  - !type:JunctionDunGen
    width: 3
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: LuaHaunted
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFHaunted
    presets:
    - LuaWow
    - LuaTall
    - LuaHive
    - LuaSpine
    - LuaCluster

  - !type:WormCorridorDunGen
    width: 3
    tile: FloorCaveDrought

  - !type:CorridorClutterDunGen
    contents: HauntedClutter

  - !type:BoundaryWallDunGen
    tile: FloorCaveDrought
    wall: WallRock

- type: dungeonConfig
  id: LuaSnowyLabs
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFSnowyLabs
    presets:
    - LuaGrid
    - LuaFork
    - LuaBucket
    - LuaRing

  - !type:CorridorDunGen
    width: 3
    tile: FloorWhite

  - !type:DungeonEntranceDunGen
    count: 3
    tile: FloorWhite
    contents: NFSnowyLabsEntrance

  - !type:RoomEntranceDunGen
    tile: FloorWhite
    contents: NFBaseAirlock

  - !type:WallMountDunGen
    contents: NFSnowyLabsWalls
    tile: FloorWhite

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorWhite

  - !type:JunctionDunGen
    width: 3
    tile: FloorWhite
    contents: NFBaseAirlock

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: LuaLavaMercenary
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFLavaMercenary
    presets:
    - LuaCross
    - LuaWings

  - !type:CorridorDunGen
    width: 3
    tile: FloorDark

  - !type:DungeonEntranceDunGen
    count: 3
    tile: FloorDark
    contents: NFMercenaryAirlock

  - !type:RoomEntranceDunGen
    tile: FloorDark
    contents: NFMercenaryAirlock

  - !type:EntranceFlankDunGen
    tile: FloorDark
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorDark
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFLavaMercenaryWallMounts
    tile: FloorDark

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorDark

  - !type:JunctionDunGen
    width: 3
    tile: FloorDark
    contents: NFMercenaryAirlock

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: LuaVirologyLab
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFVirologyLab
    presets:
    - LuaGrid
    - LuaSpine
    - LuaFork
    - LuaRing

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 3
    tile: FloorSteel
    contents: NFVirologyAirlock

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFVirologyAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFScienceLabsWalls
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFVirologyAirlock

  - !type:CornerClutterDunGen
    contents: NFBaseClutter
